version: "3.2"

networks:
    bridge2:
        driver: bridge

services:
    nodejs:
        image: jelastic/nodejs:13.8.0-npm
        restart: unless-stopped
        volumes:
            - ./:/var/www/crawler
        ports:
            - "3001:3001"
        command: ["/bin/sh", "-c", "cd /var/www/crawler && npm run start"]
        networks:
            - bridge2
    mongodb:
        image: bitnami/mongodb:4.2.3
        restart: unless-stopped
        ports:
            - "27017:27017"
        networks:
            - bridge2
    nginx:
        image: nginx:latest
        volumes:
            - ./docker/nginx/prod.conf:/etc/nginx/conf.d/prod.conf
            - ./front/:/front
        ports:
            - "8081:80"
        restart: unless-stopped
        networks:
            - bridge2
